# This is a basic mathematical interpretation of a simple RNN. In practice, more sophisticated variants like LSTM (Long Short-Term Memory) and GRU (Gated Recurrent Unit) are often used to address issues like vanishing gradients and better capture long-term dependencies.

In [1]:
import numpy as np

Dense:- This represents a **fully connected layer** (also known as a "dense" layer or "feed-forward" layer). In a Dense layer, every neuron in the layer is connected to every neuron in the preceding layer. These layers are commonly **used** in various neural network architectures **for learning complex patterns and relationships in the data**, often serving as output layers or intermediate layers in deep learning models.

SimpleRNN:- SimpleRNN layers are designed to process sequential data, where the output at a given time step depends not only on the current input but also on the previous hidden state. They are a fundamental building block for tasks involving time series, natural language processing, and other sequential data.

In [2]:
from tensorflow.keras.models import Sequential #It provides a straightforward way to create and organize the layers 
                                                # of a deep learning model in a sequential fashion. 

from tensorflow.keras.layers import SimpleRNN, Dense

2025-08-23 20:30:24.651957: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-08-23 20:30:27.048169: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-08-23 20:30:27.942468: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1755961228.711025    4658 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1755961228.883651    4658 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1755961230.375040    4658 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linkin

In [3]:
# Generate some sample data
X = np.array([[i+j for j in range(5)] for i in range(100)])
y = np.array([i+5 for i in range(100)])

In [4]:
y

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104])

In [5]:
# Reshape the data for RNN input (samples, time steps, features)
X = X.reshape((X.shape[0], X.shape[1], 1)) #It keeps the original number of rows and columns, but adds a 
                                           # new dimension of size 1 at the end.
#This is often done to prepare data for certain machine learning models that expect a specific number of 
#dimensions, such as convolutional neural networks that often process image data with channels as the last dimension.
    

In [6]:
X

array([[[  0],
        [  1],
        [  2],
        [  3],
        [  4]],

       [[  1],
        [  2],
        [  3],
        [  4],
        [  5]],

       [[  2],
        [  3],
        [  4],
        [  5],
        [  6]],

       [[  3],
        [  4],
        [  5],
        [  6],
        [  7]],

       [[  4],
        [  5],
        [  6],
        [  7],
        [  8]],

       [[  5],
        [  6],
        [  7],
        [  8],
        [  9]],

       [[  6],
        [  7],
        [  8],
        [  9],
        [ 10]],

       [[  7],
        [  8],
        [  9],
        [ 10],
        [ 11]],

       [[  8],
        [  9],
        [ 10],
        [ 11],
        [ 12]],

       [[  9],
        [ 10],
        [ 11],
        [ 12],
        [ 13]],

       [[ 10],
        [ 11],
        [ 12],
        [ 13],
        [ 14]],

       [[ 11],
        [ 12],
        [ 13],
        [ 14],
        [ 15]],

       [[ 12],
        [ 13],
        [ 14],
        [ 15],
        [ 16]],


In [7]:
# Define the RNN model
#units=32 is the number of hidden units in the SimpleRNN layer.
#The full input tensor for a SimpleRNN layer should have the shape (batch_size, timesteps, input_features)
#X.shape[1] represents the number of timesteps in each sequence.
#X.shape[2] represents the number of features per timestep. 
Num_model = Sequential([
    SimpleRNN(units=32, input_shape=(X.shape[1], X.shape[2]), activation='relu'),
    Dense(1)
])

2025-08-23 20:31:00.865492: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
/home/kashika/anaconda3/lib/python3.9/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [8]:
# Compile the model
Num_model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
Num_model.fit(X, y, epochs=25, batch_size=25)

Epoch 1/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 562.1304
Epoch 2/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 171.1600
Epoch 3/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 17.8351
Epoch 4/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 20.7057
Epoch 5/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 49.4385
Epoch 6/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 28.7266
Epoch 7/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 4.4138
Epoch 8/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.2337
Epoch 9/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 11.7771
Epoch 10/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1611
Epoch 11/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.6754
Epoch 12/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.3346
Epoch 13/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.6017
Epoch 14/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.1270
Epoch 15/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.8112
Epoch 16/25
4/4 ━━━━━━━━━

In [9]:
# Test the model
test_input = np.array([[i+j for j in range(5)] for i in range(100, 110)])
test_input = test_input.reshape((test_input.shape[0], test_input.shape[1], 1))
predicted_output = Num_model.predict(test_input)
test_input

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step


array([[[100],
        [101],
        [102],
        [103],
        [104]],

       [[101],
        [102],
        [103],
        [104],
        [105]],

       [[102],
        [103],
        [104],
        [105],
        [106]],

       [[103],
        [104],
        [105],
        [106],
        [107]],

       [[104],
        [105],
        [106],
        [107],
        [108]],

       [[105],
        [106],
        [107],
        [108],
        [109]],

       [[106],
        [107],
        [108],
        [109],
        [110]],

       [[107],
        [108],
        [109],
        [110],
        [111]],

       [[108],
        [109],
        [110],
        [111],
        [112]],

       [[109],
        [110],
        [111],
        [112],
        [113]]])

In [10]:
# Print the predicted output
print("Predicted Output:")
print(predicted_output.flatten())

Predicted Output:
[106.439545 107.480965 108.52236  109.56377  110.60516  111.64658
 112.68799  113.7294   114.7708   115.812195]


# Let's create a simple RNN using Keras with some sample data. In this example, we'll use a sequence of numbers to predict the next number in the sequence.

In [11]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

# Generate some sample data
np.random.seed(0)
sequence_length = 10
X = np.random.rand(100, sequence_length)
y = np.sum(X, axis=1)

# Reshape the data for RNN input (samples, time steps, features)
X = X.reshape((X.shape[0], X.shape[1], 1))

# Define the RNN model
model = Sequential([
    SimpleRNN(units=32, input_shape=(X.shape[1], X.shape[2]), activation='relu'),
    Dense(1)
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(X, y, epochs=10, batch_size=8)

# Test the model
test_input = np.random.rand(10).reshape((1, sequence_length, 1))
predicted_output = model.predict(test_input)

# Print the predicted output
print("Predicted Output:", predicted_output[0, 0])

Epoch 1/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 26.7911
Epoch 2/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 26.3617 
Epoch 3/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 22.9372 
Epoch 4/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 20.0605 
Epoch 5/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.5619 
Epoch 6/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0023
Epoch 7/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4788
Epoch 8/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2776 
Epoch 9/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2622
Epoch 10/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2508
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step
Predicted Output: 4.695024
